export const USER_LOGIN = {
    POSTING: "POSTING_CREDENTIALS",
    POSTED: "POSTED_CREDENTIALS",
    SUCCESS: "LOGIN_SUCCESS",
    ERROR: "LOGIN_ERROR",
    LOGGED_IN: "USER_LOGGED_IN",
    LOGGED_OUT: "USER_LOGGED_OUT"
}

export const USER_AUTHENTICATION = {
    AUTHENTICATING: "AUTHENTICATING_USER",
    AUTHENTICATED: "USER_AUTHENTICATED",
    NOT_AUTHENTICATED: "USER_NOT_AUTHENTICATED"
};


export const USER_REGISTRATION = {


};